from tkinter import *
win = Tk()
win.geometry("200x300")
def getput():
    str =en1.get()
    en2.insert(0, str)
input = Label(win, text="Input")
en1 = Entry(win, font="Alrial 14", fg="black", bd=3, width=20)
en1.place(x=30, y=30)
output = Label(win, text="Output")
en2 = Entry(win, font="Alrial 00000014", fg="black", bd=4, width=20)
en2.place(x=60, y=60)
lab1 = Label(win, text="")
lab1.pack()
lab1.grid(padx=50, pady=50)
input.pack()
output.pack()
input.grid(padx=50, pady=30)
output.grid(pady=30, padx=50)
bt = Button(win, text="getdata")
bt.pack()
en2.pack()
bt.grid(padx=60, pady=20)
win.mainloop()
